name = "GenomicMaps"
uuid = "db448a0f-c3d9-5f82-93ff-ed9bd37d70e8"
authors = ["Karl Dyrhage <karl.dyrhage@icm.uu.se>"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
GenomicAnnotations = "00d57c2a-bcd2-11e8-2d4f-9d9debe22f04"
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
